
proxy:
  #代理配置
  host: 127.0.0.1
  port: 7890
chatgpt:
  maxToken: 2048
  model: gpt-3.5-turbo
  temperature: 0.8
  #openai的key 可以配置多个
  apiKey:
    - sk-xxxxxxxxxxxxxxx
    - sk-xxxxxxxxxxxxxxx
    - sk-xxxxxxxxxxxxxxx
wecom:
  #自建应用-应用管理详情页-AgentId
  agentId: xxxxxxx
  #自建应用-API接收消息页面-Token
  sToken: xxxxxxxxxxx
  # 企业微信管理后台-我的企业-企业信息-最下面的企业ID
  sCorpID: xxxxxxxxxx
  # 自建应用-API接收消息页面-TokEncodingAESKey
  sEncodingAESKey: xxxxxxxxxxxxxxxxxxxxxxxxx
  #自建应用-详情页的Secret
  corpSecret: xxxxxxxxxxxx
server:
  port: 9207
